// Reads the repo puzzle files -> lib/puzzles.generated.ts
// run: node scripts/gen-puzzles.mjs   (from apps/studio/)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "../../../.."); // repo root

const read = (rel) => {
  const d = readFileSync(resolve(ROOT, rel), "utf8").replace(/[^0-9]/g, "");
  const out = [];
  for (let i = 0; i + 81 <= d.length; i += 81) out.push(d.slice(i, i + 81));
  return out;
};

const NAMED = [
  "AI Escargot",
  "Inkala 2010",
  "Inkala 2012 (Everest)",
  "Platinum Blonde",
  "Golden Nugget",
  "coly013",
  "Fata Morgana",
  "Kolk 17",
  "Sudoku17 #6",
  "Sudoku17 #12",
  "Norvig hard",
  "top1465 #1",
];

const lib = {
  easy: read("puzzles/easy.txt"),
  medium: read("puzzles/medium.txt"),
  hard: read("puzzles/hard.txt"),
  benchHard: read("benchmarks/hard.txt").map((p, i) => ({ puzzle: p, name: NAMED[i] ?? `#${i + 1}` })),
};

const clues = (p) => 81 - (p.match(/0/g)?.length ?? 0);

const banner = "// AUTO-GENERATED by scripts/gen-puzzles.mjs — do not edit.\n";
const body = `
export interface LibraryPuzzle {
  puzzle: string;
  clues: number;
  label: string;
}

export const PUZZLE_LIBRARY: Record<"easy" | "medium" | "hard" | "bench-hard", LibraryPuzzle[]> = {
  easy: ${JSON.stringify(lib.easy.map((p, i) => ({ puzzle: p, clues: clues(p), label: `easy ${i + 1}` })))},
  medium: ${JSON.stringify(lib.medium.map((p, i) => ({ puzzle: p, clues: clues(p), label: `medium ${i + 1}` })))},
  hard: ${JSON.stringify(lib.hard.map((p, i) => ({ puzzle: p, clues: clues(p), label: `hard ${i + 1}` })))},
  "bench-hard": ${JSON.stringify(lib.benchHard.map((x) => ({ puzzle: x.puzzle, clues: clues(x.puzzle), label: x.name })))},
};
`;

writeFileSync(resolve(HERE, "../lib/puzzles.generated.ts"), banner + body);
console.log(
  `wrote lib/puzzles.generated.ts  (easy ${lib.easy.length}, medium ${lib.medium.length}, hard ${lib.hard.length}, bench-hard ${lib.benchHard.length})`,
);
