/**
 * Acceptance criterion for Phase 3: the TypeScript solvers reproduce
 * tests/fixtures/solver_reference.json row for row - identical solution
 * string, nodes, backtracks and terminated_reason.
 *
 * The reference was generated by the Python package (Phase 2) and independently
 * cross-checked against the original Algo runner scripts.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { solve, type SolverName } from "../src/index.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REF_PATH = resolve(HERE, "../../../../tests/fixtures/solver_reference.json");

interface Row {
  set: string;
  index: number;
  puzzle: string;
  algorithm: SolverName;
  seed: number | null;
  solution: string | null;
  solved: boolean;
  nodes: number;
  backtracks: number;
  terminated_reason: string;
  max_steps?: number;
}

const ref = JSON.parse(readFileSync(REF_PATH, "utf8")) as {
  sha256: string;
  max_steps: number;
  n_rows: number;
  rows: Row[];
};

function run(rows: Row[]): { total: number; mismatches: string[] } {
  const mismatches: string[] = [];
  for (const row of rows) {
    const r = solve(row.puzzle, row.algorithm, {
      seed: row.seed ?? undefined,
      maxSteps: row.max_steps ?? ref.max_steps,
    });
    const got = [r.solution, r.nodes, r.backtracks, r.terminatedReason];
    const want = [row.solution, row.nodes, row.backtracks, row.terminated_reason];
    if (JSON.stringify(got) !== JSON.stringify(want)) {
      mismatches.push(
        `${row.set}#${row.index} ${row.algorithm} seed=${row.seed}\n` +
          `  ref: ${JSON.stringify(want)}\n  got: ${JSON.stringify(got)}`,
      );
    }
  }
  return { total: rows.length, mismatches };
}

describe("Python parity (solver_reference.json)", () => {
  const deterministic = ref.rows.filter((r) => r.algorithm !== "min_conflicts");
  const stochastic = ref.rows.filter((r) => r.algorithm === "min_conflicts");

  it(`deterministic solvers - ${deterministic.length} rows exact`, () => {
    const { total, mismatches } = run(deterministic);
    if (mismatches.length) console.error(mismatches.slice(0, 25).join("\n"));
    expect(mismatches, `${mismatches.length}/${total} rows diverged`).toEqual([]);
  });

  it(`min_conflicts (MT19937) - ${stochastic.length} rows exact`, { timeout: 600_000 }, () => {
    const { total, mismatches } = run(stochastic);
    if (mismatches.length) console.error(mismatches.slice(0, 25).join("\n"));
    expect(mismatches, `${mismatches.length}/${total} rows diverged`).toEqual([]);
  });

  it("reference digest is the one we ported against", () => {
    expect(ref.sha256).toBe(
      "008d9f43d42adb65655aaaf18f2bdcc10a6e07a67137469e4c8cd7e1e71810e2",
    );
  });
});
